background {
  monitor=
  blur_passes=2
  color=rgba(25, 20, 20, 1.0)
  path=screenshot
}

input-field {
  monitor=
  size=20%, 5%
  check_color=rgba(eed49fff)
  fade_on_empty=false
  fail_color=rgba(ed8796ff)
  font_color=rgba(cad3f5ff)
  halign=center
  inner_color=rgba(0, 0, 0, 0.0)
  outer_color=rgba(b7bdf8ff)
  outline_thickness=3
  position=0, -20
  rounding=12
  valign=center
}

label {
  monitor=
  color=rgba(b7bdf8ff)
  font_size=50
  halign=center
  position=0%, 10%
  shadow_boost=0.300000
  shadow_color=rgba(0, 0, 0, 0.1)
  shadow_passes=2
  shadow_size=20
  text=$TIME
  valign=center
}

label {
  monitor=
  color=rgba(b7bdf8ff)
  font_size=30
  halign=center
  position=0%, 15%
  shadow_boost=0.300000
  shadow_color=rgba(0, 0, 0, 0.1)
  shadow_passes=2
  shadow_size=20
  text=cmd[update:3600000] date +'%a %b %d'
  valign=center
}
